#!/bin/bash

set -e

exec 3>&1
exec 1>&2

# path to src for concourse
src_path=$1

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-in.XXXXXX)

cat > $payload <&0

echo "Payload:" $payload

# source params
webhook_url=$(jq -r '.source.url' < $payload)

# task params
text=$(jq '.params.text // ""' < $payload)
channel=$(jq '.params.channel // null' < $payload)
username=$(jq '.params.username // null' < $payload)
icon_url=$(jq '.params.icon_url // null' < $payload)
icon_emoji=$(jq '.params.icon_emoji // null' < $payload)
version_file=$(jq -r '.params.version_file // ""' < $payload)

# evaluate variables in the text
version=$(cat $src_path/$version_file)
text="\"$(eval echo $text)\""

body="{\"text\": ${text}, \"username\": ${username}, \"icon_url\": ${icon_url}, \"icon_emoji\": ${icon_emoji}, \"channel\": ${channel}}"

curl -X POST --data-urlencode "payload=$body" $webhook_url

jq -n '{version:{ref:0}}' >&3
